### ISSUE TITLE
PR link is overridden with `repository` field

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-agent-changelog-tool#108]
There is a current bug in `build` logic, where the tool uses the probably the `repo` flag instead of using `pr` field.

Example fragment:
```yaml
kind: feature
summary: Prepare packaging for endpoint and asc files
pr: https://github.com/elastic/beats/pull/20186
```

`build` log line:
```
2022/09/20 16:45:12 1595842182-Prepare-packaging-for-endpoint-and-asc-files.yaml: check if the PR field is correct in changelog: GET https://api.github.com/repos/elastic/elastic-agent/pulls/20186: 404 Not Found []
```
